baomidou/dynamic-datasource

- src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAdvisor.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
自定义切面的模式下,数据源增加DS注解一样的解析流程,可以从header,session中获取数据
例如
```java
@Configuration
public class DynamicConfiguration {
@Bean
public DynamicDataSourceConfigure dynamicDataSourceConfigure() {
return DynamicDataSourceConfigure.config()
.regexMatchers("com.baomidou.samples.nest.service.impl.*select.*", "#session.dsName")
.regexMatchers("com.baomidou.samples.nest.service.impl.*find.*", "#header.organization")
.expressionMatchers("execution(* com.baomidou.samples.nest.service.impl.*.select*(..))", "mysql");
}
}
```
多租户场景中,如果是分库模式(每个租户一个数据库,应用是同一个),每个请求默认可以分发到对应的数据库中, 特殊需要切换数据的情况,可以根据@DS进行替换
> 自定义切面的模式下,数据源增加DS注解一样的解析流程,可以从header,session中获取数据

- src/main/java/com/baomidou/dynamic/datasource/processor/DsSpelExpressionProcessor.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
在定义 DsProcessor 的地方,设置 spelExpressionProcessor.setParserContext(ParserContext.TEMPLATE_EXPRESSION); 后,
可以自定义模板取值方式.
设置:  spelExpressionProcessor.setParserContext(ParserContext.TEMPLATE_EXPRESSION); 
取值参数从 #param 改为 #{#param},  对于已经应用表达式#param的用户, 请谨慎设置这个参数
> 支持 spel 表达式的默认格式

- src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
DynamicRoutingDataSource 目前管理数据源的地方是 LinkedHashMap,  改为 ConcurrentHashMap  。
Spring的健康检查接口会便利这个HashMap。  当发生并发时，会报错。
> 数据源映射改为 ConcurrentHashMap

- src/main/java/com/baomidou/dynamic/datasource/creator/BasicDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/CompositeDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/DataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/DruidDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/HikariDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/JndiDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/provider/AbstractDataSourceProvider.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
DataSourceCreator 的规则，对外部扩展不友好。通过集成spring的Order方式， 支持外部扩增数据源创建器。
当DruidDataSource不存在时，DataSourceCreator 也无法默认选择。  这里修复了spring创建 DruidDataSourceCreator 的方式
> 重构DataSourceCreator的创建规则， 修复不存在DruidDataSource类时， 无法自动创建。

- src/main/java/com/baomidou/dynamic/datasource/support/DataSourceClassResolver.java
支持如下情况获取DS的注解
@Mapper
public interface OrderItemDao extends BaseDao<OrderItemEntity> {}
@DS("master")
public interface BaseDao<T> extends BaseMapper<T> {}
需求：动态改变DS的值，只需在父类接口标识DS注解，反射时根据需要动态修改即可。
无需标识所有子类接口，易于管理等。
版本3.0.0是支持的
> 支持从父类接口获取DS注解

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
自定义DruidDataSourceCreator等时可沿用现有顺序，如下图所示
> 调整DataSourceCreator默认顺序访问级别

- pom.xml
- src/main/java/com/baomidou/dynamic/datasource/ds/GroupDataSource.java
- src/main/java/com/baomidou/dynamic/datasource/exception/CannotSelectDataSourceException.java
- src/main/java/com/baomidou/dynamic/datasource/plugin/MasterSlaveAutoRoutingPlugin.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceHealthCheckConfiguration.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceProperties.java
- src/main/java/com/baomidou/dynamic/datasource/strategy/DynamicDataSourceStrategy.java
- src/main/java/com/baomidou/dynamic/datasource/strategy/LoadBalanceDynamicDataSourceStrategy.java
- src/main/java/com/baomidou/dynamic/datasource/strategy/RandomDynamicDataSourceStrategy.java
- src/main/java/com/baomidou/dynamic/datasource/support/DbHealthIndicator.java
- src/main/java/com/baomidou/dynamic/datasource/support/HealthCheckAdapter.java
- src/main/java/com/baomidou/dynamic/datasource/toolkit/DynamicDataSourceContextHolder.java
主从分离修复mp兼容。
主从分离的查询方式增加6个参数的查询， 当启用 mybatis-plus 的分页查询插件时， 会调用 simpleExecutor 的6个参数的查询
优化健康检查的配置和选择方式。
启用健康检查时  
1. 从库健康，可选从库， 从库不健康，打印日志，并选择主库
2. 主库无论如何都可以被选择, 即使主库的健康检查是失败的
> optimize  纯分页兼容mp和健康检查优化 

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
设定默认的 `ymlDynamicDataSourceProvider` 为 `@Order(0)`，从而使得使用方可以准确地控制 `DynamicRoutingDataSource` 中的 `providers` 注入顺序，以实现同名数据源按照优先级覆盖的效果
> 让默认的DynamicDataSourceProvider优先级为0

- core/src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionFactory.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionProxy.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/DsPropagation.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/LocalTxUtil.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/SavePointHolder.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/TransactionalTemplate.java
> feat:增加多数据源事务传播属性NESTED

- core/src/main/java/com/baomidou/dynamic/datasource/creator/DruidDataSourceCreator.java
- core/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidConfig.java
你好，基于此issues https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/487 发现目前项目确实缺少关于 druid 的timeBetweenConnectErrorMillis 的配置。
我在本地 dynamic-datasource-samples 项目中实际添加属性测试后，初始化后的 DruidDataSource 的 timeBetweenConnectErrorMillis  依旧采用了默认值 500，故提了此pull Request。
另外，我觉得后续需要实时补齐各类DataSource 的配置实属不是一件简单的事情，会考虑继承各类DataSource的配置这种方式，从而后续只需要更新 DataSource 的版本么？
期待你的回复。
> [Feature]Druid DataSource timeBetweenConnectErrorMillis Config

- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
Fix for the issue: https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/518;
It works for me, but I didn't test it for every supported datasource.
> fix ArrayStoreException during parsing annotations

- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
`com.baomidou.dynamic.datasource.provider.DynamicDataSourceProvider#loadDataSources` 可能会返回null，进而在`com.baomidou.dynamic.datasource.DynamicRoutingDataSource#afterPropertiesSet`中触发npe问题
比如`com.baomidou.dynamic.datasource.provider.AbstractJdbcDataSourceProvider#loadDataSources`的实现会在出现db异常的时候返回一个null
> fix: NPE when add datasources from provider. 

- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionFactory.java
https://github.com/dynamic-datasource/dynamic-datasource-samples.git
示例代码中,代码内两个service添加事务
@DS("product")
@DSTransactional(propagation = DsPropagation.NESTED)
导致最后主事务判断出错仍不提交事务
并且tx不关闭,下次进入锁死
> REQUIRED主事务内多个NESTED次事务不提交事务bug

- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionFactory.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/SavePointHolder.java
- [√ ] Bugfix
这个主要原因是由于当初想通过每个连接的保存点名称计数，根据调用栈的深度来释放掉SavePointHolder对象，当到达外层调用栈时最后一个savepoint会返回0(即第一次为savepoint0)，但是如果某一层级多个嵌套事务的话就会导致order连接创建出savepoint计数为1的保存点，所以当保存点释放、回滚时会出现即使SavePointHolder持有的savepoint集合为空(已经释放回滚干净)但计数未<=0不满足条件，无法删除空持有的SavePointHolder对象，因此影响主事务提交|回滚。今天那个pr虽然会再次判断这个savePointHolder持有的savepoints集合是否为空来作为存在保存点的条件但是仍然会多出一个空持有对象，因此通过将保存点释放、回滚时删除savepoint集合持有对象(SavePointHolder)的条件改为为SavePointHolder中savepoints集合是否为空。
#531
> fix:主事务内多个嵌套事务，导致影响主事务提交|回滚

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/toolkit/CryptoUtils.java
解决 加密工具类 javax.crypto.IllegalBlockSizeException: Data must not be longer than 53 bytes
// 测试代码
String url = "jdbc:mysql://192.168.211.131:3306/agile?allowMultiQueries=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false";
System.out.println(CryptoUtils.encrypt(url));
> 最大加密字节数 53 ，超出最大字节数需要分组加密； 最大解密字节数 64 ，超出最大字节数需要分组解密

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidConfigUtil.java
filter->filters
druid的拦截器名称配置属性是filters而不是filter，反射的时候是获取不到值的。
https://github.com/baomidou/dynamic-datasource/blob/master/dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidConfig.java
```
@Getter
@Setter
public class DruidConfig {
private String filters;
}
```
> fix druid filter init bug

- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAopConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAopConfiguration.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/annotation/BasicAttribute.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAnnotationInterceptor.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/aop/DynamicLocalTransactionInterceptor.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/support/DataSourceClassResolver.java
- [ √] Bugfix
- [√ ] Code style
修复@DSTransactional 无法获取类|接口|接口方法的注解属性，统一注解属性解析逻辑并将DataSourceClassResolver类中获取注解元信息的AnnotatedElementUtils.getMergedAnnotationAttributes()方法改为findMergedAnnotationAttributes()，前者不能获取到接口方法的注解元信息，导致可能导致切点切到但获取不到信息的情况。
#542
> fix @DSTransactional 无法获取注解属性|统一属性解析逻辑

- .github/workflows/ci.yml
- CONTRIBUTING.md
- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
- pom.xml
- Fixes #465.
- Fixes #535.
- Open and Fix NativeTest by Spring Framework under GraalVM CE.
- `DynamicRoutingDataSource` has design flaws. This class attempts to inject a `List<DynamicDataSourceProvider>` Spring Bean into a non-container environment, which causes the Spring Framework to deliberately take over this class and set a NoArgConstructor for this class with an unaligned parameter list. 
- As a fix, I added a AllArgsConstructor for `DynamicRoutingDataSource` to avoid https://github.com/baomidou/dynamic-datasource/actions/runs/6080472779/job/16494489274?pr=560 display, injected `List<DynamicDataSourceProvider>`  is null. 
- Similarly, Alibaba Druid's Spring …
> Open and Fix NativeTest by Spring Framework under GraalVM CE

- README.md
- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceProperties.java
- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- dynamic-datasource-spring-boot-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v1/AddRemoveDatasourceTest.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v3/AddRemoveDatasourceTest.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/DataSourceActiveDetector.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/DataSourceDestroyer.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/DefaultDataSourceDestroyer.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/Dhcp2DataSourceActiveDetector.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/DruidDataSourceActiveDetector.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/destroyer/HikariDataSourceActiveDetector.java
Fixes #578
添加运行时优雅关闭数据源的功能，该特性可以通过配置spring.datasource.dynamic.gracy-destory = true 打开。
打开后，在运行时销毁数据源将会开启异步任务延迟销毁数据源。对HikariCP，druid，DHCP2能够支持检测是否含有活跃连接，在没有活跃连接的情况下立即关闭数据源，至多10s，超时后会直接强制关闭；对于不支持的数据源10s后再关闭数据源。
在dynamic-datasource调用destroy的时候强制销毁，不进行异步关闭。
优雅关闭数据源的代码中每次进行异步关闭都会开启一个线程池，从实际情况来看，覆盖数据源配置或者移除数据源配置是一个很低频的操作，并不会产生不良影响。
更新了使用文档
> feat: gracy destory datasource 

- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAssistConfiguration.java
- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAopConfiguration.java
- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAopConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
1. 由于Advisor会优先初始化,故相关@Bean应加: @Role(BeanDefinition.ROLE_INFRASTRUCTURE) 以消除:is not eligible for getting processed by all BeanPostProcessors
2. 去除@EnableConfigurationProperties(DynamicDataSourceProperties.class) 改为static方式配置是为了加@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
3. spring 5.2+ 配置类如不内部不存在@Bean方法引用应加: proxyBeanMethods = false 以去除不必要代理类 肖：ie: `@Configuration(proxyBeanMethods = false)`
此PR是了消除启动时的以下日志:
```
[restartedMain] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[376] - Bean 'spring.datasource.dynamic-com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties' of type [com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for …
```
> perf: @Bean初始化优化, 以消除日志:is not eligible for getting processed by all BeanPostProcessors

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/enums/XADataSourceEnum.java
项目中使用 mysql-connector-java 5.1 版本的时候，需要使用老版的 MysqlXADataSource 才能创建 atomikos 数据源
> feat: 增加 MySQL Connector/J 5.1 XADataSource 的支持

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/basic/BasicDataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/beecp/BeeCpDataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/dbcp/Dbcp2DataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidDataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/hikaricp/HikariDataSourceCreator.java
1. 修复(#653)
2. 为所有的数据源创建时进行初始化的都添加统一的异常包装返回.
为什么不对延迟加载的也做处理?
我能想到的处理办法时是对原始数据源进行一层wrapper, 都是在getConnection的时候进行初始化的，但是如何对数据源创建失败是一个比较难以判断的事情也没有多大的必要
> fix 数据源创建失败缺少cause(#653)
