baomidou/dynamic-datasource

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidConfig.java
Fixing type mismatch causes the equals method to always be false
> fix:properties type mismatch

- pom.xml
- src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAdvisor.java
Incorrect identification of inheritance classes and incorrect switching of data sources when using parent methods.
Example: Mybatis Plus.
I'm trying to fix
> fix:DynamicDataSourceConfigure incorrect match target class

- src/main/java/com/baomidou/dynamic/datasource/provider/AbstractDataSourceProvider.java
- [X ] Bugfix
pollName优先使用外部设置
> pollName优先使用外部设置

- src/main/java/com/baomidou/dynamic/datasource/support/ScriptRunner.java
支持通配符扫描schema文件
支持扫描多个schema文件
[关联的issues](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/227)
> h2执行单元测试，支持通配符扫描schema文件

- src/main/java/com/baomidou/dynamic/datasource/creator/DruidDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/creator/HikariDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/provider/AbstractJdbcDataSourceProvider.java
JDBC4 以后已经不需要主动进行 DriverClass 的主动加载了，所以无需强制配置此属性。
考虑兼容性，所以当用户主动配置时，保留原来逻辑
> :art: 调整driverClassName为非必须属性

- src/main/java/com/baomidou/dynamic/datasource/creator/DruidDataSourceCreator.java
- Bugfix
动态数据创建时，配置各个数据独立的超时回收时间，设置错误
> fix-bug:动态数据创建时，配置各个数据独立的超时回收时间，设置错误

- src/main/java/com/baomidou/dynamic/datasource/ds/ItemDataSource.java
修复报错： java.lang.IllegalArgumentException: object is not an instance of declaring class
> 修复动态关闭数据源的bug

- src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
- src/main/java/com/baomidou/dynamic/datasource/creator/JndiDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/ds/GroupDataSource.java
原先的方式必须是删除了数据源后，才能添加数据源。
现在改为: 新的数据源覆盖老的数据源， 然后关闭老数据源的连接
> 添加数据源可以覆盖老的数据源

- pom.xml
- src/main/java/com/baomidou/dynamic/datasource/annotation/DSTransactional.java
- src/main/java/com/baomidou/dynamic/datasource/aop/DynamicTransactionAdvisor.java
- src/main/java/com/baomidou/dynamic/datasource/ds/AbstractRoutingDataSource.java
- src/main/java/com/baomidou/dynamic/datasource/ds/proxy/ConnectionFactory.java
- src/main/java/com/baomidou/dynamic/datasource/ds/proxy/ConnectionProxy.java
- src/main/java/com/baomidou/dynamic/datasource/ds/proxy/TransactionContext.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
> 增加多数据源统一提交和回滚的功能

- src/main/java/com/baomidou/dynamic/datasource/ds/AbstractRoutingDataSource.java
- src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionFactory.java
> 优化代理数据源处理逻辑

- src/main/java/com/baomidou/dynamic/datasource/creator/HikariDataSourceCreator.java
Support lazy init HikariDataSource.
Use parameterless construction and HikariConfig copyState method to init datasource.
Both support HikariCp 2.x and 3.x.
> Support lazy init HikariDataSource.

- src/main/java/com/baomidou/dynamic/datasource/processor/DsSpelExpressionProcessor.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
Support BeanResolver in SpelDsProcess
Add beanResolver into SpelDsProcess and use beanFactory to init beanResolver and SpelDsProcess
> Support BeanResolver in SpelDsProcess

- src/main/java/com/baomidou/dynamic/datasource/ds/ItemDataSource.java
override interface: 'Wrapper' in ItemDataSource
Conform to the 'java.sql' design, support the upper framework to obtain the real data source from DynamicRoutingDataSource and ItemDataSource.
> feat: override interface: 'Wrapper' in ItemDataSource

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
- [✅ ] Bugfix
Note modification
> #Dbcp2创建器注释错误修改

- src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
1、DynamicRoutingDataSource.closeDataSource增加判断dataSource是否为AutoCloseable
> 增加判断dataSource是否为AutoCloseable

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidConfig.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidConsts.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidStatConfig.java
> 增加慢sql日志级别配置项

- src/main/java/com/baomidou/dynamic/datasource/aop/DynamicDataSourceAnnotationAdvisor.java
- src/main/java/com/baomidou/dynamic/datasource/aop/DynamicLocalTransactionInterceptor.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.java
1. 新增对`@DSTransactional` 注解对类的支持 #387
2. 对`DynamicDataSourceAnnotationAdvisor` 初始化构造入参修改为`MethodInterceptor `接口
> 新增对@DSTransactional 注解对类的支持 #387

- src/main/java/com/baomidou/dynamic/datasource/support/DataSourceClassResolver.java
> 修复 @DS优先级 #407

- src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionFactory.java
- src/main/java/com/baomidou/dynamic/datasource/tx/ConnectionProxy.java
- src/main/java/com/baomidou/dynamic/datasource/tx/LocalTxUtil.java
\@DSTransactional批量提交本地事务异常，抛出异常
cover issue: #423
> throw exception in local transaction

- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidLogConfigUtil.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidStatConfigUtil.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidWallConfigUtil.java
- src/main/java/com/baomidou/dynamic/datasource/toolkit/DsConfigUtil.java
解决DruidConfig的stat、wall属性使用Map接受参数了，DruidStatConfigUtil在进行反射赋值的时候会报错
> 解决DruidConfig的stat、wall属性使用Map接受参数了，DruidStatConfigUtil在进行反射赋值的时候会报错

- src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration
:sparkles: 支持 Spring Boot 新版自动配置
> :sparkles: 支持 Spring Boot 新版自动配置

- pom.xml
- src/main/java/com/baomidou/dynamic/datasource/creator/DruidDataSourceCreator.java
- src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/druid/DruidConfig.java
> 支持配置druid新版本socketTimeout、connectTimeout属性

- .gitignore
- pom.xml
- Fixes #471.
- Migrating from Jakarta EE 9 to Jakarta EE 10.
- Ignore VSCode configuration files.
> Migrating from Jakarta EE 9 to Jakarta EE 10

- core/pom.xml
- core/src/main/java/com/baomidou/dynamic/datasource/creator/AtomikosDataSourceCreator.java
- core/src/main/java/com/baomidou/dynamic/datasource/enums/XADataSourceEnum.java
- core/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DataSourceProperty.java
- core/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
- core/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceProperties.java
- core/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/atomikos/AtomikosConfig.java
- core/src/main/java/com/baomidou/dynamic/datasource/support/DdConstants.java
- core/src/main/java/com/baomidou/dynamic/datasource/tx/AtomikosTransactionFactory.java
- pom.xml
- [v] Feature
增加适配atomikos数据源,支持同一个事务下多次切换数据源
> feat:增加适配atomikos数据源,支持同一个事务下多次切换数据源

- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/LocalTxUtil.java
修复rollback方法打印日志信息的错误，commit 改为rollback 
> fix:fix log output information error

- dynamic-datasource-spring-boot3-starter/src/main/resources/META-INF/native-image/com.baomidou/dynamic-datasource-spring-boot3-starter/resource-config.json
- dynamic-datasource-spring-boot3-starter/src/test/resources/META-INF/native-image/dynamic-datasource-spring-boot3-starter-test-metadata/resource-config.json
- For https://github.com/baomidou/dynamic-datasource/issues/565 .
- Add missing condition entries in GraalVM Reachability Metadata.
- Null.
> Add missing condition entries in GraalVM Reachability Metadata

- README.md
> feat: update-readme, format configuration yaml

- README.md
I missed a level. :(
I missed a level. :(
> fix: update-readme, format configuration yaml

- .gitignore
gitignore add virtual machine crash logs
> chore:  gitignore add virtual machine crash logs

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidConfigUtil.java
config.getConnectionProperties()可能出现空指针问题
#604
> fix(dynamic-datasource-creator):解决当存在publicKey时，druid数据源创建异常问题

- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAopConfiguration.java
> fix 修复 启动警告问题

- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/DynamicRoutingDataSource.java
Refactor(close-datasource): #614 
在分组数据库map删除后删除datasource
所有测试本地通过
- [*] Refactor
> perf(close-datasource): 在分组数据库map删除后删除datasource

- dynamic-datasource-spring-boot-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v1/DsTransactionalTest.java
- dynamic-datasource-spring-boot-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v1/service/tx/OrderService.java
- dynamic-datasource-spring-boot3-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v3/DsTransactionalTest.java
- dynamic-datasource-spring-boot3-starter/src/test/java/com/baomidou/dynamic/datasource/fixture/v3/service/tx/OrderService.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/TransactionContext.java
- dynamic-datasource-spring/src/main/java/com/baomidou/dynamic/datasource/tx/TransactionalTemplate.java
- [√ ] Bugfix
#620 修复多数据源事务回调中开启事务的死循环问题
> fix:事务后置回调中开启事务死循环

- dynamic-datasource-creator/pom.xml
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/DataSourceProperty.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/c3p0/C3p0Config.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/c3p0/C3p0DataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/enums/DdConstants.java
- dynamic-datasource-spring-boot-common/pom.xml
- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceProperties.java
- pom.xml
> Feat:增加对c3p0数据源支持

- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/check/SeataDataSourceProxyChecker.java
> feat: 增加对seata框架代理数据源的检测 (#704)

- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/check/SeataDataSourceProxyChecker.java
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/check/SeataDataSourceProxyChecker.java
增加对seata框架代理数据源的检测 (https://github.com/baomidou/dynamic-datasource/issues/704)
> 增加对seata框架代理数据源的检测 (#704)

- dynamic-datasource-creator/pom.xml
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/DataSourceProperty.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/oracleucp/OracleUcpConfig.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/oracleucp/OracleUcpDataSourceCreator.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/enums/DdConstants.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/toolkit/DsStrUtils.java
- dynamic-datasource-spring-boot-common/pom.xml
- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceCreatorAutoConfiguration.java
- dynamic-datasource-spring-boot-common/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceProperties.java
- pom.xml
- [✅ ] Feature
增加对OracleUCP数据源支持
> feat:增加对OracleUCP数据源支持 (#724)

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidConfig.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidDataSourceCreator.java
> feat: DruidConfig支持线程池参数

- dynamic-datasource-spring-boot-starter/pom.xml
- dynamic-datasource-spring-boot-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourcePoolMetricsAutoConfiguration.java
- dynamic-datasource-spring-boot-starter/src/main/resources/META-INF/spring.factories
- dynamic-datasource-spring-boot3-starter/pom.xml
- dynamic-datasource-spring-boot3-starter/src/main/java/com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourcePoolMetricsAutoConfiguration.java
- dynamic-datasource-spring-boot3-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- [√] Feature
- 新增 DynamicDataSourcePoolMetricsAutoConfiguration 类，支持HikariCP多数据源连接池监控指标
> feat(metrics): 添加 HikariCP连接池监控指标

- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidConfig.java
- dynamic-datasource-creator/src/main/java/com/baomidou/dynamic/datasource/creator/druid/DruidDataSourceCreator.java
> 新增druid数据源callback配置
